### ISSUE TITLE
Colour palette

### ISSUE THREAD

**Issue by MattCowgill** [runapp-aus/runapp_website#1]
I think we should adopt one of the palettes from the [`ochRe` package](https://github.com/ropenscilabs/ochRe) for the website. Any thoughts?

**Comment by wfmackey** [comment]
Great suggestion. I like the look of `namatjira_div`?

**Comment by MattCowgill** [comment]
That’s what I’d been thinking too! Yep I’m keen

**Comment by shelbyso** [comment]
Only a minor quibble with the `namatjira_div` palette – the light beige `#d8c0a8` and light blue `#d8f0f0` colours are washed out under a white or grey background, especially when there is some transparency. Otherwise the palette looks nice!

**Comment by MattCowgill** [comment]
Using `namatjira`
