### ISSUE TITLE
The links to the posts don't work

### ISSUE THREAD

**Issue by williamlai2** [runapp-aus/runapp_website#5]
These links:

https://runapp-aus.github.io/runapp_website/posts/welcome/ 

https://runapp-aus.github.io/runapp_website/posts/2021-03-25-data-science-in-the-public-sector-1/ 

Don't lead anywhere. 

> 404
File not found
The site configured at this address does not contain the requested file.

The pages do exist on GitHub though: https://github.com/runapp-aus/runapp_website/tree/master/_posts

**Comment by MattCowgill** [comment]
Hi @williamlai2 thanks for filing this issue. I've fixed it now.
